default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: treebook_development

test:
  <<: *default
  database: treebook_test

production:
  <<: *default
  database: treebook_production
  username: treebook
  password: <%= ENV['CHAT-API_DATABASE_PASSWORD'] %>
